/* Auto-generated from source/ui.html - do not edit by hand. */
/* Regenerate: python3 source/tools/embed_ui.py source/ui.html source/html.h */
static const char HTML_PAGE[] =
  "<!DOCTYPE html>\n"
  "<html lang='en'>\n"
  "<head>\n"
  "<meta charset='UTF-8'>\n"
  "<meta name='viewport' content='width=device-width, initial-scale=1.0'>\n"
  "<title>Plugins Mgr :4002</title>\n"
  "<style>\n"
  "    * { margin: 0; padding: 0; box-sizing: border-box; -webkit-tap-highlight-color: transparent }\n"
  "    .tab, .shut, .card, .card-btn, .modal-footer .btn, .sort-btn, .close, #confirmOk, #confirmCancel { -webkit-tap-highlight-color: transparent }\n"
  "    :root {\n"
  "      --bg: #06060e; --s1: #0c0c1a; --bd: #1a1a35;\n"
  "      --ac: #0070ff; --ac2: #00bbff; --gl: rgba(0,112,255,.15);\n"
  "      --tx: #d0d0e4; --dm: #505068;\n"
  "      --ok: #00dd77; --er: #ff2244; --lb: #040408;\n"
  "      --indigo-glow: rgba(80,50,180,.28); --indigo-light: #a78bfa;\n"
  "      --cyan-dim: rgba(0,210,255,.15); --cyan: #38bdf8;\n"
  "      --tr: #fbbf24; --tr-dim: rgba(251,191,36,.15);\n"
  "    }\n"
  "    body {\n"
  "      font-family: -apple-system, system-ui, sans-serif;\n"
  "      background: radial-gradient(ellipse at 10% 40%, #0c1424, var(--bg) 65%);\n"
  "      color: var(--tx); height: 100vh;\n"
  "      display: flex; flex-direction: column; overflow: hidden;\n"
  "    }\n"
  "    ::-webkit-scrollbar { width: 5px }\n"
  "    ::-webkit-scrollbar-track { background: transparent }\n"
  "    ::-webkit-scrollbar-thumb { background: var(--bd); border-radius: 3px }\n"
  "    nav {\n"
  "      height: 48px; background: var(--s1);\n"
  "      border-bottom: 1px solid var(--bd);\n"
  "      display: flex; align-items: center;\n"
  "      padding: 0 20px; gap: 12px;\n"
  "      flex-shrink: 0; position: relative;\n"
  "    }\n"
  "    nav::after {\n"
  "      content: ''; position: absolute; bottom: 0; left: 0; right: 0; height: 1px;\n"
  "      background: linear-gradient(90deg, transparent, var(--ac), transparent); opacity: .3;\n"
  "    }\n"
  "    .logo {\n"
  "      font-size: 14px; font-weight: 800; letter-spacing: 3px;\n"
  "      text-transform: uppercase; margin-right: 12px;\n"
  "      background: linear-gradient(135deg, var(--ac), var(--ac2));\n"
  "      -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text;\n"
  "    }\n"
  "    .logo .version {\n"
  "      font-size: 10px; font-weight: 500; color: var(--dm);\n"
  "      letter-spacing: 0.5px; text-transform: none;\n"
  "      background: none; -webkit-text-fill-color: var(--dm);\n"
  "      margin-left: 4px;\n"
  "    }\n"
  "    .tab {\n"
  "      background: none; border: 1px solid transparent; color: var(--dm);\n"
  "      font-size: 11px; font-weight: 600; padding: 5px 14px;\n"
  "      cursor: pointer; border-radius: 16px; transition: all .2s;\n"
  "      letter-spacing: .5px; text-transform: uppercase;\n"
  "    }\n"
  "    .tab:hover { color: var(--tx); border-color: var(--bd) }\n"
  "    .tab.active {\n"
  "      color: #fff; background: var(--ac); border-color: var(--ac);\n"
  "      box-shadow: 0 0 12px var(--gl);\n"
  "    }\n"
  "    .mobile-filter-btn {\n"
  "      display: none;\n"
  "      background: var(--ac); border: 1px solid var(--ac); color: #fff;\n"
  "      font-size: 11px; font-weight: 600; padding: 5px 14px;\n"
  "      cursor: pointer; border-radius: 16px; transition: all .2s;\n"
  "      letter-spacing: .5px; text-transform: uppercase;\n"
  "      box-shadow: 0 0 12px var(--gl);\n"
  "    }\n"
  "    .spacer { flex: 1 }\n"
  "    .status {\n"
  "      font-size: 11px; color: var(--dm); letter-spacing: .5px;\n"
  "    }\n"
  "    .status span { color: var(--tx); font-weight: 600 }\n"
  "    .shut {\n"
  "      background: none; border: 1px solid var(--er); color: var(--er);\n"
  "      padding: 5px 12px; border-radius: 16px; cursor: pointer;\n"
  "      font-size: 10px; font-weight: 700;\n"
  "      letter-spacing: .5px; text-transform: uppercase; transition: all .2s;\n"
  "    }\n"
  "    .shut:hover { background: var(--er); color: #fff }\n"
  "    .shut svg, .card-btn svg, .modal-footer .btn svg {\n"
  "      width: 16px; height: 16px;\n"
  "      display: inline-block; vertical-align: middle;\n"
  "      pointer-events: none;\n"
  "    }\n"
  "    .filter-bar {\n"
  "      height: 44px; background: var(--s1);\n"
  "      border-bottom: 1px solid var(--bd);\n"
  "      display: flex; align-items: center;\n"
  "      padding: 0 20px; gap: 10px;\n"
  "      flex-shrink: 0;\n"
  "    }\n"
  "    .filter-bar label {\n"
  "      font-size: 10px; font-weight: 700; color: var(--dm);\n"
  "      text-transform: uppercase; letter-spacing: 1px;\n"
  "    }\n"
  "    .filter-bar select {\n"
  "      background: var(--bg); border: 1px solid var(--bd); color: var(--tx);\n"
  "      padding: 4px 10px; border-radius: 8px; font-size: 12px;\n"
  "      cursor: pointer; outline: none; width: 100%; max-width: 300px;\n"
  "    }\n"
  "    .filter-bar select:focus { border-color: var(--ac) }\n"
  "    .filter-bar input[type=text] {\n"
  "      background: var(--bg); border: 1px solid var(--bd); color: var(--tx);\n"
  "      padding: 4px 10px; border-radius: 8px; font-size: 12px;\n"
  "      outline: none; width: 100%; max-width: 180px;\n"
  "    }\n"
  "    .filter-bar input[type=text]:focus { border-color: var(--ac) }\n"
  "    .sort-btn {\n"
  "      background: var(--bg); border: 1px solid var(--bd); color: var(--tx);\n"
  "      padding: 4px 10px; border-radius: 8px; font-size: 12px;\n"
  "      cursor: pointer; outline: none; transition: all .2s;\n"
  "      font-family: monospace; min-width: 32px;\n"
  "    }\n"
  "    .sort-btn:hover { border-color: var(--ac); color: var(--ac) }\n"
  "    .trophy-btn {\n"
  "      background: var(--tr-dim); border: 1px solid var(--tr); color: var(--tr);\n"
  "      padding: 4px 10px; border-radius: 8px; font-size: 12px;\n"
  "      cursor: pointer; outline: none; transition: all .2s;\n"
  "      display: flex; align-items: center; justify-content: center;\n"
  "      min-width: 32px; box-shadow: 0 0 12px var(--tr-dim);\n"
  "    }\n"
  "    .trophy-btn svg {\n"
  "      width: 16px; height: 16px; display: block;\n"
  "      pointer-events: none; fill: currentColor;\n"
  "    }\n"
  "    .trophy-btn:hover { background: rgba(251,191,36,.25); }\n"
  "    .trophy-btn.active {\n"
  "      color: var(--dm); background: var(--bg);\n"
  "      border-color: var(--bd); box-shadow: none;\n"
  "    }\n"
  "    .filter-bar .count {\n"
  "      font-size: 11px; color: var(--dm); margin-left: auto;\n"
  "    }\n"
  "    .filter-bar .count span { color: var(--tx); font-weight: 600 }\n"
  "    .gallery {\n"
  "      flex: 1; overflow-y: auto; padding: 16px 20px;\n"
  "    }\n"
  "    .grid {\n"
  "      display: grid;\n"
  "      grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));\n"
  "      gap: 12px;\n"
  "    }\n"
  "    .card {\n"
  "      background: var(--s1); border: 1px solid var(--bd);\n"
  "      border-radius: 10px; overflow: hidden;\n"
  "      cursor: pointer; transition: all .2s;\n"
  "      position: relative;\n"
  "    }\n"
  "    .card:hover {\n"
  "      border-color: var(--ac);\n"
  "      box-shadow: 0 0 16px var(--gl);\n"
  "      transform: translateY(-2px);\n"
  "    }\n"
  "    .card-thumb {\n"
  "      width: 100%; aspect-ratio: 16/9;\n"
  "      background: var(--bg); display: flex;\n"
  "      align-items: center; justify-content: center;\n"
  "      overflow: hidden; position: relative;\n"
  "    }\n"
  "    .card-thumb img {\n"
  "      width: 100%; height: 100%; object-fit: cover;\n"
  "    }\n"
  "    .card-thumb .placeholder {\n"
  "      color: var(--dm); font-size: 32px;\n"
  "    }\n"
  "    .card-thumb svg { width: 44px; height: 44px; stroke: var(--dm); fill: none; stroke-width: 1.5; }\n"
  "    .card.enabled .card-thumb svg { stroke: var(--ac2); filter: drop-shadow(0 0 8px var(--gl)); }\n"
  "    .trophy-inline { margin-right: 4px; }\n"
  "    .trophy-inline img,\n"
  "    .trophy-inline svg {\n"
  "      height: 1em; width: auto;\n"
  "      vertical-align: middle;\n"
  "      display: inline;\n"
  "      pointer-events: none;\n"
  "    }\n"
  "    .type-badge {\n"
  "      display: inline-block;\n"
  "      font-size: 9px; font-weight: 700;\n"
  "      padding: 1px 5px; border-radius: 4px;\n"
  "      text-transform: uppercase; letter-spacing: .5px;\n"
  "      margin-right: 4px; vertical-align: middle;\n"
  "    }\n"
  "    .type-badge.video { background: var(--indigo-glow); color: var(--indigo-light); }\n"
  "    .type-badge.photo { background: var(--cyan-dim); color: var(--cyan); }\n"
  "    .type-badge.on { background: rgba(0,221,119,.15); color: var(--ok); }\n"
  "    .type-badge.off { background: rgba(255,34,68,.15); color: var(--er); }\n"
  "    .card-info {\n"
  "      padding: 10px 12px;\n"
  "    }\n"
  "    .card-title {\n"
  "      font-size: 12px; font-weight: 600; color: var(--tx);\n"
  "      white-space: nowrap; overflow: hidden; text-overflow: ellipsis;\n"
  "    }\n"
  "    .card-meta {\n"
  "      font-size: 10px; color: var(--dm); margin-top: 3px;\n"
  "      display: flex; justify-content: space-between;\n"
  "    }\n"
  "    .card-actions {\n"
  "      display: flex; gap: 6px; margin-top: 8px;\n"
  "    }\n"
  "    .card-btn {\n"
  "      flex: 1; padding: 5px 0; border: 1px solid var(--bd);\n"
  "      background: none; color: var(--dm); font-size: 10px;\n"
  "      font-weight: 600; border-radius: 6px; cursor: pointer;\n"
  "      text-transform: uppercase; letter-spacing: .5px;\n"
  "      transition: all .2s;\n"
  "    }\n"
  "    .card-btn:hover { border-color: var(--ac); color: var(--ac) }\n"
  "    .card-btn.dl { border-color: var(--ac); color: var(--ac) }\n"
  "    .card-btn.dl:hover { background: var(--ac); color: #fff }\n"
  "    .card-btn.del { border-color: var(--er); color: var(--er) }\n"
  "    .card-btn.del:hover { background: var(--er); border-color: var(--er); color: #fff }\n"
  "    .modal-overlay {\n"
  "      display: none; position: fixed; inset: 0;\n"
  "      background: rgba(0,0,0,.85); z-index: 1000;\n"
  "      align-items: center; justify-content: center;\n"
  "      backdrop-filter: blur(4px);\n"
  "    }\n"
  "    .modal-overlay.active { display: flex }\n"
  "    #confirmModal {\n"
  "      position: fixed; inset: 0;\n"
  "      z-index: 1100;\n"
  "      backdrop-filter: blur(8px);\n"
  "      background: rgba(0,0,0,.92);\n"
  "    }\n"
  "    #modal.behind-confirm { backdrop-filter: blur(5px); }\n"
  "    .modal {\n"
  "      background: var(--s1); border: 1px solid var(--bd);\n"
  "      border-radius: 12px; max-width: 90vw; max-height: 90vh;\n"
  "      display: flex; flex-direction: column; overflow: hidden;\n"
  "    }\n"
  "    .modal-header {\n"
  "      display: flex; align-items: center; padding: 12px 16px;\n"
  "      border-bottom: 1px solid var(--bd); gap: 12px;\n"
  "    }\n"
  "    .modal-header .title {\n"
  "      flex: 1; font-size: 13px; font-weight: 600;\n"
  "      white-space: nowrap; overflow: hidden; text-overflow: ellipsis;\n"
  "    }\n"
  "    .modal-header .close {\n"
  "      background: none; border: none; color: var(--dm);\n"
  "      font-size: 18px; cursor: pointer; padding: 0 4px;\n"
  "    }\n"
  "    .modal-header .close:hover { color: var(--tx) }\n"
  "    .modal-body {\n"
  "      flex: 1; overflow: auto; display: flex;\n"
  "      align-items: center; justify-content: center;\n"
  "      padding: 0;\n"
  "    }\n"
  "    .modal-body img {\n"
  "      max-width: 100%; max-height: 70vh; object-fit: contain;\n"
  "    }\n"
  "    .modal-body video {\n"
  "      max-width: 100%; max-height: 70vh; outline: none;\n"
  "    }\n"
  "    .preview-wrapper {\n"
  "      position: relative;\n"
  "      display: flex;\n"
  "      align-items: center;\n"
  "      justify-content: center;\n"
  "    }\n"
  "    .preview-thumb {\n"
  "      position: absolute;\n"
  "      inset: 0;\n"
  "      width: 100%;\n"
  "      height: 100%;\n"
  "      object-fit: contain;\n"
  "      filter: blur(12px);\n"
  "      opacity: 1;\n"
  "      transition: opacity 0.3s;\n"
  "    }\n"
  "    .preview-thumb.hidden { opacity: 0 }\n"
  "    .preview-full {\n"
  "      position: relative;\n"
  "      width: 100%;\n"
  "      height: 100%;\n"
  "      object-fit: contain;\n"
  "      opacity: 0;\n"
  "      transition: opacity 0.3s;\n"
  "    }\n"
  "    .preview-full.loaded { opacity: 1 }\n"
  "    .preview-spinner {\n"
  "      position: absolute;\n"
  "      width: 40px;\n"
  "      height: 40px;\n"
  "      border: 3px solid var(--bd);\n"
  "      border-top-color: var(--ac);\n"
  "      border-radius: 50%;\n"
  "      animation: spin 0.8s linear infinite;\n"
  "      z-index: 10;\n"
  "    }\n"
  "    .preview-spinner.hidden { display: none }\n"
  "    @keyframes spin {\n"
  "      to { transform: rotate(360deg); }\n"
  "    }\n"
  "    .modal-footer {\n"
  "      display: flex; padding: 10px 16px; gap: 8px;\n"
  "      border-top: 1px solid var(--bd);\n"
  "    }\n"
  "    .modal-footer .info {\n"
  "      flex: 1; font-size: 11px; color: var(--dm);\n"
  "      display: flex; align-items: center;\n"
  "    }\n"
  "    .modal-footer .btn {\n"
  "      padding: 6px 16px; border-radius: 8px; font-size: 11px;\n"
  "      font-weight: 600; cursor: pointer; border: 1px solid var(--bd);\n"
  "      background: none; color: var(--tx); transition: all .2s;\n"
  "      text-transform: uppercase; letter-spacing: .5px;\n"
  "    }\n"
  "    .modal-footer .btn:hover { border-color: var(--ac); color: var(--ac) }\n"
  "    .modal-footer .btn.primary { background: var(--ac); border-color: var(--ac); color: #fff }\n"
  "    .modal-footer .btn.primary:hover { background: var(--ac2) }\n"
  "    .modal-footer .btn.danger { border-color: var(--er); color: var(--er) }\n"
  "    .modal-footer .btn.danger:hover { background: var(--er); color: #fff }\n"
  "    #modalDownload { border-color: var(--ac); color: var(--ac); text-decoration: none }\n"
  "    #modalDownload:hover { background: var(--ac); color: #fff }\n"
  "    .modal.confirm { max-width: 360px; width: 90%; }\n"
  "    #confirmBody { padding: 20px; font-size: 13px; color: var(--tx); text-align: center; }\n"
  "    #confirmOk { margin-left: 8px; }\n"
  "    #confirmCancel { border-color: var(--ac); color: var(--ac) }\n"
  "    #confirmCancel:hover { background: var(--ac); color: #fff }\n"
  "    .empty {\n"
  "      display: flex; flex-direction: column; align-items: center;\n"
  "      justify-content: center; height: 100%; color: var(--dm);\n"
  "    }\n"
  "    .empty .icon { font-size: 48px; margin-bottom: 12px; opacity: .5 }\n"
  "    .empty .msg { font-size: 14px; font-weight: 600 }\n"
  "    .empty .sub { font-size: 12px; margin-top: 4px; opacity: .6 }\n"
  "    .detail-table { width: 100%; border-collapse: collapse; font-size: 12px; }\n"
  "    .detail-table td { padding: 8px 16px; border-bottom: 1px solid var(--bd); word-break: break-all; }\n"
  "    .detail-table td:first-child { color: var(--dm); width: 110px; text-transform: uppercase; font-size: 10px; letter-spacing: 1px; }\n"
  "    #toast {\n"
  "      position: fixed; bottom: 18px; left: 50%; transform: translateX(-50%) translateY(20px);\n"
  "      background: var(--s1); border: 1px solid var(--ac); color: var(--tx);\n"
  "      padding: 8px 18px; border-radius: 20px; font-size: 12px; z-index: 2000;\n"
  "      opacity: 0; transition: all .25s; pointer-events: none; box-shadow: 0 0 16px var(--gl);\n"
  "    }\n"
  "    #toast.show { opacity: 1; transform: translateX(-50%) translateY(0); }\n"
  "    #toast.err { border-color: var(--er); }\n"
  "    .add-label { font-size: 10px; font-weight: 700; color: var(--dm); text-transform: uppercase; letter-spacing: 1px; margin-bottom: 4px; }\n"
  "    .add-field { background: var(--bg); border: 1px solid var(--bd); color: var(--tx); padding: 6px 10px; border-radius: 8px; font-size: 12px; outline: none; width: 100%; }\n"
  "    .add-field:focus { border-color: var(--ac) }\n"
  "    @media (max-width: 600px) {\n"
  "      .grid { grid-template-columns: repeat(auto-fill, minmax(140px, 1fr)); gap: 8px }\n"
  "      .gallery { padding: 10px 12px }\n"
  "      .filter-bar { flex-wrap: wrap; height: auto; min-height: 44px; padding: 4px 12px; gap: 6px }\n"
  "      .filter-bar label { font-size: 9px }\n"
  "      .filter-bar select { max-width: 120px; padding: 3px 6px }\n"
  "      nav { padding: 0 12px }\n"
  "      .status { display: none }\n"
  "      nav .tab { display: none }\n"
  "      .mobile-filter-btn { display: inline-block }\n"
  "    }\n"
  "</style>\n"
  "</head>\n"
  "<body>\n"
  "<nav>\n"
  "  <div class='logo'>Plugins Mgr<span class='version'>v1.0 :4002</span></div>\n"
  "  <button class='tab active' data-tab='all'>All</button>\n"
  "  <button class='tab' data-tab='enabled'>Enabled</button>\n"
  "  <button class='tab' data-tab='disabled'>Disabled</button>\n"
  "  <button class='tab' data-tab='unlisted'>Unlisted</button>\n"
  "  <button class='mobile-filter-btn' id='mobileFilter'>Filter</button>\n"
  "  <div class='spacer'></div>\n"
  "  <div class='status' id='status'><span>0</span> files</div>\n"
  "  <button class='shut' id='stopBtn' title='Stop server'>\n"
  "    <svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2'><path d='M18.36 6.64a9 9 0 1 1-12.72 0'/><line x1='12' y1='2' x2='12' y2='12'/></svg>\n"
  "    Stop\n"
  "  </button>\n"
  "</nav>\n"
  "<div class='filter-bar'>\n"
  "  <label>Section</label>\n"
  "  <select id='sectFilter'><option value=''>All sections</option></select>\n"
  "  <button class='sort-btn' id='sortBtn' title='Toggle sort'>A-Z</button>\n"
  "  <input type='text' id='search' placeholder='Search files...'>\n"
  "  <button class='sort-btn' id='uploadBtn' title='Upload file'>+ Upload</button>\n"
  "  <button class='sort-btn' id='addBtn' title='Add ini entry'>+ Entry</button>\n"
  "  <div class='count' id='count'>showing <span>0</span></div>\n"
  "</div>\n"
  "<div class='gallery'><div class='grid' id='grid'></div><div class='empty' id='empty' style='display:none'>\n"
  "  <div class='icon'>&#9673;</div>  <div class='msg'>No files found</div>\n"
  "  <div class='sub'>Upload a file or add an entry to plugins.ini</div>\n"
  "</div></div>\n"
  "<input type='file' id='fileInput' style='display:none'>\n"
  "<div class='modal-overlay' id='modal'><div class='modal' style='max-width:520px;width:90%'>\n"
  "  <div class='modal-header'><div class='title' id='modalTitle'></div>\n"
  "  <button class='close' id='modalClose'>&times;</button></div>\n"
  "  <div class='modal-body' style='display:block;padding:8px 0'><table class='detail-table' id='detailTable'></table></div>\n"
  "  <div class='modal-footer'><div class='info' id='modalInfo'></div>\n"
  "    <button class='btn danger' id='modalDelete'>Delete</button>\n"
  "    <button class='btn primary' id='modalToggle'>Toggle</button>\n"
  "  </div>\n"
  "</div></div>\n"
  "<div class='modal-overlay' id='confirmModal'><div class='modal confirm'>\n"
  "  <div class='modal-header'><div class='title'>Confirm</div></div>\n"
  "  <div id='confirmBody'></div>\n"
  "  <div class='modal-footer'><div class='info'></div>\n"
  "    <button class='btn' id='confirmCancel'>Cancel</button>\n"
  "    <button class='btn primary' id='confirmOk'>OK</button>\n"
  "  </div>\n"
  "</div></div>\n"
  "<div class='modal-overlay' id='addModal'><div class='modal' style='max-width:420px;width:90%'>\n"
  "  <div class='modal-header'><div class='title'>Add plugin entry</div>\n"
  "  <button class='close' id='addClose'>&times;</button></div>\n"
  "  <div class='modal-body' style='display:block;padding:14px 16px'>\n"
  "    <div style='margin-bottom:10px'><div class='add-label'>Section</div><select id='addSection' class='add-field'></select></div>\n"
  "    <div id='addNewWrap' style='display:none;margin-bottom:10px'><div class='add-label'>New section</div><input type='text' id='addNewSection' class='add-field' placeholder='CUSA00001'></div>\n"
  "    <div style='margin-bottom:10px'><div class='add-label'>Pick from files on disk</div><select id='addPick' class='add-field'><option value=''>-- or type filename below --</option></select></div>\n"
  "    <div style='margin-bottom:10px'><div class='add-label'>Filename + extension</div><input type='text' id='addFilename' class='add-field' placeholder='my_plugin.prx'></div>\n"
  "    <div style='font-size:11px;color:var(--dm);word-break:break-all' id='addPreview'>/data/GoldHEN/plugins/...</div>\n"
  "  </div>\n"
  "  <div class='modal-footer'><div class='info'>path is filled in automatically</div>\n"
  "    <button class='btn' id='addCancel'>Cancel</button>\n"
  "    <button class='btn primary' id='addOk'>Add</button>\n"
  "  </div>\n"
  "</div></div>\n"
  "<div id='toast'></div>\n"
  "<script>\n"
  "var S={sections:[],files:[],tab:'all',sect:'',q:'',asc:true,sel:null};\n"
  "var $=function(id){return document.getElementById(id);};\n"
  "function toast(m,e){var t=$('toast');t.textContent=m;t.className=e?'show err':'show';setTimeout(function(){t.className='';},2200);}\n"
  "function fmtSize(b){if(b<1024)return b+' B';if(b<1048576)return (b/1024).toFixed(1)+' KB';return (b/1048576).toFixed(2)+' MB';}\n"
  "function esc(s){return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');}\n"
  "function allEntries(){var r=[];S.sections.forEach(function(s){s.entries.forEach(function(e){r.push({section:s.id,path:e.path,file:e.file,enabled:e.enabled});});});return r;}\n"
  "function fileInfo(n){for(var i=0;i<S.files.length;i++)if(S.files[i].name===n)return S.files[i];return null;}\n"
  "async function load(){try{var r=await fetch('/api/plugins');var j=await r.json();S.sections=j.sections||[];S.files=j.files||[];buildSect();buildAddPick();render();}catch(e){toast('Failed to load plugins',1);}}\n"
  "function buildSect(){var s=$('sectFilter');var cur=s.value;s.innerHTML='<option value=\"\">All sections</option>';S.sections.forEach(function(x){var o=document.createElement('option');o.value=x.id;o.textContent=x.id+' ('+x.entries.length+')';s.appendChild(o);});s.value=cur;}\n"
  "function buildAddPick(){var p=$('addPick');var cur=p.value;p.innerHTML='<option value=\"\">-- or type filename below --</option>';S.files.forEach(function(f){var o=document.createElement('option');o.value=f.name;o.textContent=f.name;p.appendChild(o);});p.value=cur;}\n"
  "function filtered(){var es=allEntries();var out=[];\n"
  "  if(S.tab==='unlisted'){S.files.forEach(function(f){out.push({section:'',path:'/data/GoldHEN/plugins/'+f.name,file:f.name,enabled:false,unlisted:true});});}\n"
  "  else{es.forEach(function(e){if(S.tab==='enabled'&&!e.enabled)return;if(S.tab==='disabled'&&e.enabled)return;out.push(e);});}\n"
  "  if(S.sect)out=out.filter(function(e){return e.section===S.sect;});\n"
  "  if(S.q)out=out.filter(function(e){return e.file.toLowerCase().indexOf(S.q)>=0||e.path.toLowerCase().indexOf(S.q)>=0;});\n"
  "  out.sort(function(a,b){return S.asc?a.file.localeCompare(b.file):b.file.localeCompare(a.file);});\n"
  "  return out;}\n"
  "function badge(e){if(e.unlisted)return \"<span class='type-badge photo'>unlisted</span>\";return e.enabled?\"<span class='type-badge on'>on</span>\":\"<span class='type-badge off'>off</span>\";}\n"
  "var PUZZLE=\"<svg viewBox='0 0 24 24'><path d='M14 7V5a2 2 0 0 0-4 0v2H7a2 2 0 0 0-2 2v3h2a2 2 0 1 1 0 4H5v3a2 2 0 0 0 2 2h3v-2a2 2 0 1 1 4 0v2h3a2 2 0 0 0 2-2v-3h-2a2 2 0 1 1 0-4h2V9a2 2 0 0 0-2-2h-3z'/></svg>\";\n"
  "function render(){var list=filtered();var g=$('grid');g.innerHTML='';\n"
  "  $('empty').style.display=list.length?'none':'flex';\n"
  "  $('count').innerHTML='showing <span>'+list.length+'</span>';\n"
  "  var n=allEntries().length;$('status').innerHTML='<span>'+n+'</span> plugins';\n"
  "  list.forEach(function(e){var f=fileInfo(e.file);var sz=f?fmtSize(f.size):'missing';\n"
  "    var d=document.createElement('div');d.className='card'+(e.enabled?' enabled':'');\n"
  "    d.innerHTML=\"<div class='card-thumb'>\"+PUZZLE+\"</div><div class='card-info'><div class='card-title'>\"+esc(e.file)+\"</div><div class='card-meta'><span>\"+esc(e.section||'disk')+\"</span><span>\"+sz+\"</span></div><div style='margin-top:4px'>\"+badge(e)+\"</div><div class='card-actions'><button class='card-btn dl'>\"+(e.unlisted?'Add':(e.enabled?'Disable':'Enable'))+\"</button><button class='card-btn'>Details</button><button class='card-btn del'>X</button></div></div>\";\n"
  "    var btns=d.querySelectorAll('.card-btn');\n"
  "    btns[0].onclick=function(ev){ev.stopPropagation();if(e.unlisted)openAddModal('default',e.file);else toggle(e);};\n"
  "    btns[1].onclick=function(ev){ev.stopPropagation();openModal(e);};\n"
  "    btns[2].onclick=function(ev){ev.stopPropagation();askDelete(e);};\n"
  "    d.onclick=function(){openModal(e);};\n"
  "    g.appendChild(d);});}\n"
  "async function post(url,body){var r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});return r.json();}\n"
  "async function toggle(e){var j=await post('/api/toggle',{section:e.section,path:e.path});if(j.ok){toast('Toggled '+e.file);load();}else toast(j.error||'Toggle failed',1);}\n"
  "function openAddModal(section,file){\n"
  "  var sel=$('addSection'), newWrap=$('addNewWrap');\n"
  "  sel.innerHTML='<option value=\"\">-- select a section --</option>';\n"
  "  S.sections.forEach(function(x){var o=document.createElement('option');o.value=x.id;o.textContent=x.id;sel.appendChild(o);});\n"
  "  if(section && S.sections.some(function(x){return x.id===section;})) sel.value=section;\n"
  "  if(file) $('addFilename').value=file;\n"
  "  newWrap.style.display='none';\n"
  "  updateAddPreview();\n"
  "  $('addModal').classList.add('active');\n"
  "}\n"
  "function updateAddPreview(){\n"
  "  var filename=$('addFilename').value.trim();\n"
  "  var section=$('addSection').value || $('addNewSection').value.trim();\n"
  "  $('addPreview').textContent=section && filename ? '/data/GoldHEN/plugins/'+filename : '/data/GoldHEN/plugins/...';\n"
  "}\n"
  "async function addEntryFromModal(){\n"
  "  var filename=$('addFilename').value.trim();\n"
  "  var section=$('addSection').value || $('addNewSection').value.trim();\n"
  "  if(!filename){toast('Enter a filename + extension',1);return;}\n"
  "  if(filename.indexOf('/')>=0 || filename.indexOf('\\\\')>=0 || filename.indexOf('..')>=0){toast('Invalid filename',1);return;}\n"
  "  if(!section){toast('Select or create a section',1);return;}\n"
  "  var j=await post('/api/entry',{section:section,path:'/data/GoldHEN/plugins/'+filename,op:'add'});\n"
  "  if(j.ok){toast(j.exists?'Already exists':'Entry added');closeAddModal();load();}\n"
  "  else toast(j.error||'Add failed',1);\n"
  "}\n"
  "function closeAddModal(){$('addModal').classList.remove('active');}\n"
  "function askDelete(e){confirmBox('Delete '+e.file+'? File + ini refs are removed.',async function(){\n"
  "  var j=await post('/api/file',{name:e.file,op:'delete',clean_ini:true});\n"
  "  if(j.ok){toast('Deleted '+e.file);closeModal();load();}else toast(j.error||'Delete failed',1);});}\n"
  "var confirmCb=null;\n"
  "function confirmBox(msg,cb){$('confirmBody').textContent=msg;confirmCb=cb;$('confirmModal').classList.add('active');$('modal').classList.add('behind-confirm');}\n"
  "$('confirmOk').onclick=function(){$('confirmModal').classList.remove('active');$('modal').classList.remove('behind-confirm');if(confirmCb)confirmCb();};\n"
  "$('confirmCancel').onclick=function(){$('confirmModal').classList.remove('active');$('modal').classList.remove('behind-confirm');};\n"
  "function openModal(e){S.sel=e;var f=fileInfo(e.file);\n"
  "  $('modalTitle').textContent=e.file;\n"
  "  $('detailTable').innerHTML='<tr><td>Path</td><td>'+esc(e.path)+'</td></tr><tr><td>Section</td><td>'+esc(e.section||'(file only)')+'</td></tr><tr><td>State</td><td>'+(e.unlisted?'unlisted (not in ini)':(e.enabled?'enabled':'disabled'))+'</td></tr><tr><td>Size</td><td>'+(f?fmtSize(f.size):'not on disk')+'</td></tr>';\n"
  "  $('modalInfo').textContent=e.section?e.section+' :: '+e.file:'on disk only';\n"
  "  $('modalToggle').textContent=e.enabled?'Disable':'Enable';\n"
  "  $('modal').classList.add('active');}\n"
  "function closeModal(){$('modal').classList.remove('active');}\n"
  "$('modalClose').onclick=closeModal;\n"
  "$('modal').onclick=function(e){if(e.target===$('modal'))closeModal();};\n"
  "$('modalToggle').onclick=function(){if(!S.sel)return;var e=S.sel;closeModal();if(e.unlisted)openAddModal(e.section||'default',e.file);else toggle(e);};\n"
  "$('modalDelete').onclick=function(){if(!S.sel)return;var e=S.sel;askDelete(e);};\n"
  "document.querySelectorAll('.tab').forEach(function(t){t.onclick=function(){document.querySelectorAll('.tab').forEach(function(x){x.classList.remove('active');});t.classList.add('active');S.tab=t.getAttribute('data-tab');render();};});\n"
  "$('mobileFilter').onclick=function(){var tabs=['all','enabled','disabled','unlisted'];var i=(tabs.indexOf(S.tab)+1)%tabs.length;S.tab=tabs[i];document.querySelectorAll('.tab').forEach(function(x){x.classList.toggle('active',x.getAttribute('data-tab')===S.tab);});toast('Filter: '+S.tab);render();};\n"
  "$('sectFilter').onchange=function(e){S.sect=e.target.value;render();};\n"
  "$('search').oninput=function(e){S.q=e.target.value.toLowerCase();render();};\n"
  "$('sortBtn').onclick=function(){S.asc=!S.asc;$('sortBtn').textContent=S.asc?'A-Z':'Z-A';render();};\n"
  "$('addBtn').onclick=function(){openAddModal('default','');};\n"
  "$('addClose').onclick=closeAddModal;\n"
  "$('addCancel').onclick=closeAddModal;\n"
  "$('addOk').onclick=addEntryFromModal;\n"
  "$('addSection').onchange=function(){$('addNewWrap').style.display=$('addSection').value?'none':'block';updateAddPreview();};\n"
  "$('addNewSection').oninput=updateAddPreview;\n"
  "$('addFilename').oninput=updateAddPreview;\n"
  "$('addPick').onchange=function(){if(this.value)$('addFilename').value=this.value;updateAddPreview();};\n"
  "$('sectFilter').onchange=function(e){S.sect=e.target.value;render();};\n"
  "$('search').oninput=function(e){S.q=e.target.value.toLowerCase();render();};\n"
  "$('sortBtn').onclick=function(){S.asc=!S.asc;$('sortBtn').textContent=S.asc?'A-Z':'Z-A';render();};\n"
  "$('addBtn').onclick=function(){openAddModal('default','');};\n"
  "$('uploadBtn').onclick=function(){$('fileInput').click();};\n"
  "$('fileInput').onchange=async function(){var f=$('fileInput').files[0];if(!f)return;\n"
  "  toast('Uploading '+f.name+'...');\n"
  "  try{var r=await fetch('/api/upload?filename='+encodeURIComponent(f.name),{method:'POST',body:f});var j=await r.json();if(j.ok){toast('Uploaded '+f.name);load();}else toast(j.error||'Upload failed',1);}catch(e){toast('Upload failed',1);}\n"
  "  $('fileInput').value='';};\n"
  "$('stopBtn').onclick=function(){confirmBox('Stop the Plugins Mgr server?',async function(){try{await fetch('/api/stop',{method:'POST'});toast('Server stopped');}catch(e){toast('Server stopped');}});};\n"
  "load();\n"
  "</script>\n"
  "</body>\n"
;
